#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Precompute contact maps (L×L) and voxel grids (4×32×32×32) from the CA-only PDBs
generated by tfds_to_fasta_pdb.py. Speeds up training by caching inputs to disk.

Usage: python cache_contacts_voxels.py --pdb_dir data/casp7_assets/pdb_ca --out_dir data/casp7_cache
Requires: pip install numpy tqdm
"""
import argparse
from pathlib import Path

import numpy as np
from tqdm import tqdm


def read_ca_coords(pdb_path) -> np.ndarray:
    coords = []
    with open(pdb_path) as f:
        for line in f:
            if line.startswith("ATOM") and line[12:16].strip() == "CA":
                try:
                    x = float(line[30:38])
                    y = float(line[38:46])
                    z = float(line[46:54])
                    coords.append((x, y, z))
                except ValueError:
                    pass
    return np.asarray(coords, dtype=np.float32)


def contact_map(ca_xyz: np.ndarray, cutoff: float, max_len: int) -> np.ndarray:
    L = min(len(ca_xyz), max_len)
    C = np.zeros((max_len, max_len), dtype=np.float32)
    if L > 0:
        diff = ca_xyz[:L, None, :] - ca_xyz[None, :L, :]
        D    = np.linalg.norm(diff, axis=-1)
        C[:L, :L] = (D < cutoff).astype(np.float32)
    return C


def voxels(ca_xyz: np.ndarray, box: int, spacing: float) -> np.ndarray:
    V = np.zeros((4, box, box, box), dtype=np.float32)
    if ca_xyz.size == 0:
        return V
    half = (box // 2) * spacing
    for p in (ca_xyz - ca_xyz.mean(axis=0)):
        if np.any(np.abs(p) > half):
            continue
        idx = np.clip(((p + half) / spacing).astype(int), 0, box - 1)
        V[0, idx[0], idx[1], idx[2]] = 1.0
    return V


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pdb_dir", type=str, default="data/casp7_assets/pdb_ca")
    ap.add_argument("--out_dir", type=str, default="data/casp7_cache")
    ap.add_argument("--cutoff",  type=float, default=8.0)
    ap.add_argument("--max_len", type=int,   default=512)
    ap.add_argument("--box",     type=int,   default=32)
    ap.add_argument("--spacing", type=float, default=1.5)
    ap.add_argument("--limit",   type=int,   default=0, help="0 = all")
    args = ap.parse_args()

    pdb_dir = Path(args.pdb_dir)
    out_dir = Path(args.out_dir)
    c_dir   = out_dir / "contacts"; c_dir.mkdir(parents=True, exist_ok=True)
    v_dir   = out_dir / "voxels";   v_dir.mkdir(parents=True, exist_ok=True)

    pdb_files = sorted(pdb_dir.glob("*.pdb"))
    if args.limit:
        pdb_files = pdb_files[:args.limit]

    for pdb in tqdm(pdb_files, desc="Caching"):
        ca = read_ca_coords(pdb)
        np.save(c_dir / f"{pdb.stem}.npy", contact_map(ca, args.cutoff, args.max_len))
        np.save(v_dir / f"{pdb.stem}.npy", voxels(ca, args.box, args.spacing))

    print(f"Done. contacts -> {c_dir}, voxels -> {v_dir}")


if __name__ == "__main__":
    main()